<?php
/**
 * TimeZone
 *
 * @copyright   Copyright &copy; 2005, Katsumi Saito <katsumi@jo1upk.ymt.prug.or.jp>
 * @version     $Id: timezone.php,v 0.1 2005/03/13 16:00:00 upk Exp $
 *
 */

function set_timezone()
{
	global $language;
	$l = accept_language::split_locale_str( $language );

	if (empty($l[2])) {
		$obj_l2c = new lang2country();
		$l[2] = $obj_l2c->get_country2lang($l[1]);
	}

	$obj = new timezone( $l[2] );
	$zone = $obj->get_zone();
	$zonetime = $obj->get_zonetime(0); // FIXME: DST

	if ($zonetime == 0 || empty($zone)) {
		define('ZONE', 'UTC');
		define('ZONETIME', 0);
	}

	define('ZONE', $zone);
	define('ZONETIME', $zonetime);
}

class timezone
{
	var $country;
	var $tz = array(
		// Key - TimeZone Name			=> 0: OFFSET, 1:HOUR, 2:MINUTE, 3:ISO3166
		//					   4: ABBREV, 5:DAYLIGHT
		'Africa/Abidjan'			=> array(+1,  0,  0, 'CI', '',     0),
		'Africa/Accra'				=> array(+1,  0,  0, 'GH', '',     0),
		'Africa/Addis_Ababa'			=> array(+1,  3,  0, 'ET', '',     0),
		'Africa/Algiers'			=> array(+1,  1,  0, 'DZ', '',     0),
		'Africa/Asmera'				=> array(+1,  3,  0, 'ER', '',     0),
		'Africa/Bamako'				=> array(+1,  0,  0, 'ML', '',     0),
		'Africa/Bangui'				=> array(+1,  1,  0, 'CF', '',     0),
		'Africa/Banjul'				=> array(+1,  0,  0, 'GM', '',     0),
		'Africa/Bissau'				=> array(+1,  0,  0, 'GW', '',     0),
		'Africa/Blantyre'			=> array(+1,  2,  0, 'MW', '',     0),
		'Africa/Brazzaville'			=> array(+1,  1,  0, 'CG', '',     0),
		'Africa/Bujumbura'			=> array(+1,  2,  0, 'BI', '',     0),
		'Africa/Cairo'				=> array(+1,  2,  0, 'EG', 'EET',  1),
		'Africa/Casablanca'			=> array(+1,  0,  0, 'MA', '',     0),
		'Africa/Ceuta'				=> array(+1,  1,  0, 'ES', '',     1),
		'Africa/Conakry'			=> array(+1,  0,  0, 'GN', '',     0),
		'Africa/Dakar'				=> array(+1,  0,  0, 'SN', '',     0),
		'Africa/Dar_es_Salaam'			=> array(+1,  3,  0, 'TZ', '',     0),
		'Africa/Djibouti'			=> array(+1,  3,  0, 'DJ', '',     0),
		'Africa/Douala'				=> array(+1,  1,  0, 'CM', '',     0),
		'Africa/El_Aaiun'			=> array(+1,  0,  0, 'EH', '',     0),
		'Africa/Freetown'			=> array(+1,  0,  0, 'SL', '',     0),
		'Africa/Gaborone'			=> array(+1,  2,  0, 'BW', '',     0),
		'Africa/Harare'				=> array(+1,  2,  0, 'ZW', 'CAT',  0),
		'Africa/Johannesburg'			=> array(+1,  2,  0, 'ZA', 'SAST', 0),
		'Africa/Kampala'			=> array(+1,  3,  0, 'UG', '',     0),
		'Africa/Khartoum'			=> array(+1,  3,  0, 'SD', '',     0),
		'Africa/Kigali'				=> array(+1,  2,  0, 'RW', '',     0),
		'Africa/Kinshasa'			=> array(+1,  1,  0, 'CD', '',     0),
		'Africa/Lagos'				=> array(+1,  1,  0, 'NG', 'WAT',  0),
		'Africa/Libreville'			=> array(+1,  1,  0, 'GA', '',     0),
		'Africa/Lome'				=> array(+1,  0,  0, 'TG', '',     0),
		'Africa/Luanda'				=> array(+1,  1,  0, 'AO', '',     0),
		'Africa/Lubumbashi'			=> array(+1,  2,  0, 'CD', '',     0),
		'Africa/Lusaka'				=> array(+1,  2,  0, 'ZM', '',     0),
		'Africa/Malabo'				=> array(+1,  1,  0, 'GQ', '',     0),
		'Africa/Maputo'				=> array(+1,  2,  0, 'MZ', '',     0),
		'Africa/Maseru'				=> array(+1,  2,  0, 'LS', '',     0),
		'Africa/Mbabane'			=> array(+1,  2,  0, 'SZ', '',     0),
		'Africa/Mogadishu'			=> array(+1,  3,  0, 'SO', '',     0),
		'Africa/Monrovia'			=> array(+1,  0,  0, 'LR', '',     0),
		'Africa/Nairobi'			=> array(+1,  3,  0, 'KE', 'EAT',  0),
		'Africa/Ndjamena'			=> array(+1,  1,  0, 'TD', '',     0),
		'Africa/Niamey'				=> array(+1,  1,  0, 'NE', '',     0),
		'Africa/Nouakchott'			=> array(+1,  0,  0, 'MR', '',     0),
		'Africa/Ouagadougou'			=> array(+1,  0,  0, 'BF', '',     0),
		'Africa/Porto-Novo'			=> array(+1,  1,  0, 'BJ', '',     0),
		'Africa/Sao_Tome'			=> array(+1,  0,  0, 'ST', '',     0),
		'Africa/Timbuktu'			=> array(+1,  0,  0, 'ML', '',     0),
		'Africa/Tripoli'			=> array(+1,  2,  0, 'LY', '',     0),
		'Africa/Tunis'				=> array(+1,  1,  0, 'TN', 'CET',  0),
		'Africa/Windhoek'			=> array(+1,  1,  0, 'NA', 'WAST', 1),
		'America/Adak'				=> array(-1, 10,  0, 'US', 'HAST', 1),
		'America/Anchorage'			=> array(-1,  9,  0, 'US', 'AKST', 1),
		'America/Anguilla'			=> array(-1,  4,  0, 'AI', '',     0),
		'America/Antigua'			=> array(-1,  4,  0, 'AG', '',     0),
		'America/Araguaina'			=> array(-1,  3,  0, 'BR', '',     0),
		'America/Argentina/Buenos_Aires'	=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/Catamarca'		=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/ComodRivadavia'	=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/Cordoba'		=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/Jujuy'		=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/La_Rioja'		=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/Mendoza'		=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/Rio_Gallegos'	=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/San_Juan'		=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/Tucuman'		=> array(-1,  3,  0, 'AR', '',     0),
		'America/Argentina/Ushuaia'		=> array(-1,  3,  0, 'AR', '',     0),
		'America/Aruba'				=> array(-1,  4,  0, 'AW', '',     0),
		'America/Asuncion'			=> array(-1,  4,  0, 'PY', 'PYST', 1),
		'America/Atka'				=> array(-1, 10,  0, '',   '',     1),
		'America/Bahia'				=> array(-1,  3,  0, 'BR', '',     0),
		'America/Barbados'			=> array(-1,  4,  0, 'BB', '',     0),
		'America/Belem'				=> array(-1,  3,  0, 'BR', 'BRT',  0),
		'America/Belize'			=> array(-1,  6,  0, 'BZ', '',     0),
		'America/Boa_Vista'			=> array(-1,  4,  0, 'BR', '',     0),
		'America/Bogota'			=> array(-1,  5,  0, 'CO', 'COT',  0),
		'America/Boise'				=> array(-1,  7,  0, 'US', '',     1),
		'America/Buenos_Aires'			=> array(-1,  3,  0, '',   'ART',  0),
		'America/Cambridge_Bay'			=> array(-1,  7,  0, 'CA', '',     1),
		'America/Campo_Grande'			=> array(-1,  4,  0, 'BR', '',     1),
		'America/Cancun'			=> array(-1,  6,  0, 'MX', '',     1),
		'America/Caracas'			=> array(-1,  4,  0, 'VE', 'VET',  0),
		'America/Catamarca'			=> array(-1,  3,  0, '',   '',     0),
		'America/Cayenne'			=> array(-1,  3,  0, 'GF', '',     0),
		'America/Cayman'			=> array(-1,  5,  0, 'KY', '',     0),
		'America/Chicago'			=> array(-1,  6,  0, 'US', 'CST',  1),
		'America/Chihuahua'			=> array(-1,  7,  0, 'MX', '',     1),
		'America/Cordoba'			=> array(-1,  3,  0, '',   '',     0),
		'America/Costa_Rica'			=> array(-1,  6,  0, 'CR', '',     0),
		'America/Cuiaba'			=> array(-1,  4,  0, 'BR', 'AMT',  1),
		'America/Curacao'			=> array(-1,  4,  0, 'AN', '',     0),
		'America/Danmarkshavn'			=> array(+1,  0,  0, 'GL', 'GMT',  0),
		'America/Dawson'			=> array(-1,  8,  0, 'CA', '',     1),
		'America/Dawson_Creek'			=> array(-1,  7,  0, 'CA', '',     0),
		'America/Denver'			=> array(-1,  7,  0, 'US', 'MST',  1),
		'America/Detroit'			=> array(-1,  5,  0, 'US', '',     1),
		'America/Dominica'			=> array(-1,  4,  0, 'DM', '',     0),
		'America/Edmonton'			=> array(-1,  7,  0, 'CA', '',     1),
		'America/Eirunepe'			=> array(-1,  5,  0, 'BR', 'ACT',  0),
		'America/El_Salvador'			=> array(-1,  6,  0, 'SV', '',     0),
		'America/Ensenada'			=> array(-1,  8,  0, '',   '',     1),
		'America/Fort_Wayne'			=> array(-1,  5,  0, '',   '',     0),
		'America/Fortaleza'			=> array(-1,  3,  0, 'BR', '',     0),
		'America/Glace_Bay'			=> array(-1,  4,  0, 'CA', '',     1),
		'America/Godthab'			=> array(-1,  3,  0, 'GL', 'WGT',  1),
		'America/Goose_Bay'			=> array(-1,  4,  0, 'CA', '',     1),
		'America/Grand_Turk'			=> array(-1,  5,  0, 'TC', '',     1),
		'America/Grenada'			=> array(-1,  4,  0, 'GD', '',     0),
		'America/Guadeloupe'			=> array(-1,  4,  0, 'GP', '',     0),
		'America/Guatemala'			=> array(-1,  6,  0, 'GT', '',     0),
		'America/Guayaquil'			=> array(-1,  5,  0, 'EC', 'ECT',  0),
		'America/Guyana'			=> array(-1,  4,  0, 'GY', '',     0),
		'America/Halifax'			=> array(-1,  4,  0, 'CA', 'AST',  1),
		'America/Havana'			=> array(-1,  5,  0, 'CU', 'CST',  1),
		'America/Hermosillo'			=> array(-1,  7,  0, 'MX', '',     0),
		'America/Indiana/Indianapolis'		=> array(-1,  5,  0, '',   '',     0),
		'America/Indiana/Knox'			=> array(-1,  5,  0, 'US', '',     0),
		'America/Indiana/Marengo'		=> array(-1,  5,  0, 'US', '',     0),
		'America/Indiana/Vevay'			=> array(-1,  5,  0, 'US', '',     0),
		'America/Indianapolis'			=> array(-1,  5,  0, 'US', '',     0),
		'America/Inuvik'			=> array(-1,  7,  0, 'CA', '',     1),
		'America/Iqaluit'			=> array(-1,  5,  0, 'CA', '',     1),
		'America/Jamaica'			=> array(-1,  5,  0, 'JM', '',     0),
		'America/Jujuy'				=> array(-1,  3,  0, '',   '',     0),
		'America/Juneau'			=> array(-1,  9,  0, 'US', '',     1),
		'America/Kentucky/Louisville'		=> array(-1,  5,  0, '',   '',     1),
		'America/Kentucky/Monticello'		=> array(-1,  5,  0, 'US', '',     1),
		'America/Knox_IN'			=> array(-1,  5,  0, '',   '',     0),
		'America/La_Paz'			=> array(-1,  4,  0, 'BO', '',     0),
		'America/Lima'				=> array(-1,  5,  0, 'PE', 'PET',  0),
		'America/Los_Angeles'			=> array(-1,  8,  0, 'US', 'PST',  1),
		'America/Louisville'			=> array(-1,  5,  0, 'US', '',     1),
		'America/Maceio'			=> array(-1,  3,  0, 'BR', '',     0),
		'America/Managua'			=> array(-1,  6,  0, 'NI', '',     0),
		'America/Manaus'			=> array(-1,  4,  0, 'BR', '',     0),
		'America/Martinique'			=> array(-1,  4,  0, 'MQ', '',     0),
		'America/Mazatlan'			=> array(-1,  7,  0, 'MX', '',     1),
		'America/Mendoza'			=> array(-1,  3,  0, '',   '',     0),
		'America/Menominee'			=> array(-1,  6,  0, 'US', '',     1),
		'America/Merida'			=> array(-1,  6,  0, 'MX', '',     1),
		'America/Mexico_City'			=> array(-1,  6,  0, 'MX', '',     1),
		'America/Miquelon'			=> array(-1,  3,  0, 'PM', 'PMST', 1),
		'America/Monterrey'			=> array(-1,  6,  0, 'MX', '',     1),
		'America/Montevideo'			=> array(-1,  3,  0, 'UY', 'UYT',  1),
		'America/Montreal'			=> array(-1,  5,  0, 'CA', '',     1),
		'America/Montserrat'			=> array(-1,  4,  0, 'MS', '',     0),
		'America/Nassau'			=> array(-1,  5,  0, 'BS', '',     1),
		'America/New_York'			=> array(-1,  5,  0, 'US', 'EST',  1),
		'America/Nipigon'			=> array(-1,  5,  0, 'CA', '',     1),
		'America/Nome'				=> array(-1,  9,  0, 'US', '',     1),
		'America/Noronha'			=> array(-1,  2,  0, 'BR', 'FNT',  0),
		'America/North_Dakota/Center'		=> array(-1,  6,  0, 'US', '',     1),
		'America/Panama'			=> array(-1,  5,  0, 'PA', '',     0),
		'America/Pangnirtung'			=> array(-1,  5,  0, 'CA', '',     1),
		'America/Paramaribo'			=> array(-1,  3,  0, 'SR', '',     0),
		'America/Phoenix'			=> array(-1,  7,  0, 'US', '',     0),
		'America/Port-au-Prince'		=> array(-1,  5,  0, 'HT', '',     0),
		'America/Port_of_Spain'			=> array(-1,  4,  0, 'TT', '',     0),
		'America/Porto_Acre'			=> array(-1,  5,  0, '',   '',     0),
		'America/Porto_Velho'			=> array(-1,  4,  0, 'BR', 'AMT',  0),
		'America/Puerto_Rico'			=> array(-1,  4,  0, 'PR', '',     0),
		'America/Rainy_River'			=> array(-1,  6,  0, 'CA', '',     1),
		'America/Rankin_Inlet'			=> array(-1,  6,  0, 'CA', '',     1),
		'America/Recife'			=> array(-1,  3,  0, 'BR', '',     0),
		'America/Regina'			=> array(-1,  6,  0, 'CA', '',     0),
		'America/Rio_Branco'			=> array(-1,  5,  0, 'BR', '',     0),
		'America/Rosario'			=> array(-1,  3,  0, '',   '',     0),
		'America/Santiago'			=> array(-1,  4,  0, 'CL', 'CLST', 1),
		'America/Santo_Domingo'			=> array(-1,  4,  0, 'DO', '',     0),
		'America/Sao_Paulo'			=> array(-1,  3,  0, 'BR', 'BRT',  1),
		'America/Scoresbysund'			=> array(-1,  1,  0, 'GL', 'EGT',  1),
		'America/Shiprock'			=> array(-1,  7,  0, 'US', '',     1),
		'America/St_Johns'			=> array(-1,  3, 30, 'CA', 'NST',  1),
		'America/St_Kitts'			=> array(-1,  4,  0, 'KN', '',     0),
		'America/St_Lucia'			=> array(-1,  4,  0, 'LC', '',     0),
		'America/St_Thomas'			=> array(-1,  4,  0, 'VI', '',     0),
		'America/St_Vincent'			=> array(-1,  4,  0, 'VC', '',     0),
		'America/Swift_Current'			=> array(-1,  6,  0, 'CA', '',     0),
		'America/Tegucigalpa'			=> array(-1,  6,  0, 'HN', '',     0),
		'America/Thule'				=> array(-1,  4,  0, 'GL', '',     1),
		'America/Thunder_Bay'			=> array(-1,  5,  0, 'CA', '',     1),
		'America/Tijuana'			=> array(-1,  8,  0, 'MX', '',     1),
		'America/Toronto'			=> array(-1,  5,  0, 'CA', '',     1),
		'America/Tortola'			=> array(-1,  4,  0, 'VG', '',     0),
		'America/Vancouver'			=> array(-1,  8,  0, 'CA', '',     1),
		'America/Virgin'			=> array(-1,  4,  0, '',   '',     0),
		'America/Whitehorse'			=> array(-1,  8,  0, 'CA', '',     1),
		'America/Winnipeg'			=> array(-1,  6,  0, 'CA', '',     1),
		'America/Yakutat'			=> array(-1,  9,  0, 'US', '',     1),
		'America/Yellowknife'			=> array(-1,  7,  0, 'CA', '',     1),
		'Antarctica/Casey'			=> array(+1,  8,  0, 'AQ', '',     0),
		'Antarctica/Davis'			=> array(+1,  7,  0, 'AQ', '',     0),
		'Antarctica/DumontDUrville'		=> array(+1, 10,  0, 'AQ', '',     0),
		'Antarctica/Mawson'			=> array(+1,  6,  0, 'AQ', '',     0),
		'Antarctica/McMurdo'			=> array(+1, 12,  0, 'AQ', '',     1),
		'Antarctica/Palmer'			=> array(-1,  4,  0, 'AQ', '',     1),
		'Antarctica/Rothera'			=> array(-1,  3,  0, 'AQ', '',     0),
		'Antarctica/South_Pole'			=> array(+1, 12,  0, 'AQ', '',     1),
		'Antarctica/Syowa'			=> array(+1,  3,  0, 'AQ', '',     0),
		'Antarctica/Vostok'			=> array(+1,  6,  0, 'AQ', '',     0),
		'Arctic/Longyearbyen'			=> array(+1,  1,  0, 'SJ', '',     1),
		'Asia/Aden'				=> array(+1,  3,  0, 'YE', '',     0),
		'Asia/Almaty'				=> array(+1,  6,  0, 'KZ', '',     1),
		'Asia/Amman'				=> array(+1,  2,  0, 'JO', '',     1),
		'Asia/Anadyr'				=> array(+1, 12,  0, 'RU', 'ANAT', 1),
		'Asia/Aqtau'				=> array(+1,  4,  0, 'KZ', '',     1),
		'Asia/Aqtobe'				=> array(+1,  5,  0, 'KZ', '',     1),
		'Asia/Ashgabat'				=> array(+1,  5,  0, 'TM', '',     0),
		'Asia/Ashkhabad'			=> array(+1,  5,  0, '',   '',     0),
		'Asia/Baghdad'				=> array(+1,  3,  0, 'IQ', 'AST',  1),
		'Asia/Bahrain'				=> array(+1,  3,  0, 'BH', '',     0),
		'Asia/Baku'				=> array(+1,  4,  0, 'AZ', '',     1),
		'Asia/Bangkok'				=> array(+1,  7,  0, 'TH', '',     0),
		'Asia/Beirut'				=> array(+1,  2,  0, 'LB', '',     1),
		'Asia/Bishkek'				=> array(+1,  5,  0, 'KG', '',     1),
		'Asia/Brunei'				=> array(+1,  8,  0, 'BN', '',     0),
		'Asia/Calcutta'				=> array(+1,  5, 30, 'IN', 'IST',  0),
		'Asia/Choibalsan'			=> array(+1,  9,  0, 'MN', '',     1),
		'Asia/Chongqing'			=> array(+1,  8,  0, 'CN', '',     0),
		'Asia/Chungking'			=> array(+1,  8,  0, '',   '',     0),
		'Asia/Colombo'				=> array(+1,  6,  0, 'LK', '',     0),
		'Asia/Dacca'				=> array(+1,  6,  0, '',   '',     0),
		'Asia/Damascus'				=> array(+1,  2,  0, 'SY', 'EET',  1),
		'Asia/Dhaka'				=> array(+1,  6,  0, 'BD', 'BDT',  0),
		'Asia/Dili'				=> array(+1,  9,  0, '',   '',     0),
		'Asia/Dubai'				=> array(+1,  4,  0, 'AE', '',     0),
		'Asia/Dushanbe'				=> array(+1,  5,  0, 'TJ', '',     0),
		'Asia/Gaza'				=> array(+1,  2,  0, 'PS', '',     1),
		'Asia/Harbin'				=> array(+1,  8,  0, 'CN', '',     0),
		'Asia/Hong_Kong'			=> array(+1,  8,  0, '',   'HKT',  0),
		'Asia/Hovd'				=> array(+1,  7,  0, 'MN', '',     1),
		'Asia/Irkutsk'				=> array(+1,  8,  0, 'RU', 'IRKT', 1),
		'Asia/Istanbul'				=> array(+1,  2,  0, '',   '',     1),
		'Asia/Jakarta'				=> array(+1,  7,  0, 'ID', 'WIT',  0),
		'Asia/Jayapura'				=> array(+1,  9,  0, 'ID', 'EIT',  0),
		'Asia/Jerusalem'			=> array(+1,  2,  0, 'IL', 'IST',  1),
		'Asia/Kabul'				=> array(+1,  4, 30, 'AF', 'AFT',  0),
		'Asia/Kamchatka'			=> array(+1, 12,  0, 'RU', 'PETT', 1),
		'Asia/Karachi'				=> array(+1,  5,  0, 'PK', 'PKT',  0),
		'Asia/Kashgar'				=> array(+1,  8,  0, 'CN', '',     0),
		'Asia/Katmandu'				=> array(+1,  5, 45, 'NP', 'NPT',  0),
		'Asia/Krasnoyarsk'			=> array(+1,  7,  0, 'RU', 'KRAT', 1),
		'Asia/Kuala_Lumpur'			=> array(+1,  8,  0, 'MY', '',     0),
		'Asia/Kuching'				=> array(+1,  8,  0, 'MY', '',     0),
		'Asia/Kuwait'				=> array(+1,  3,  0, 'KW', '',     0),
		'Asia/Macao'				=> array(+1,  8,  0, '',   '',     0),
		'Asia/Macau'				=> array(+1,  8,  0, 'MO', '',     0),
		'Asia/Magadan'				=> array(+1, 11,  0, 'RU', 'MAGT', 1),
		'Asia/Makassar'				=> array(+1,  8,  0, 'ID', 'CIT',  0),
		'Asia/Manila'				=> array(+1,  8,  0, 'PH', 'PHT',  0),
		'Asia/Muscat'				=> array(+1,  4,  0, 'OM', 'GST',  0),
		'Asia/Nicosia'				=> array(+1,  2,  0, 'CY', '',     1),
		'Asia/Novosibirsk'			=> array(+1,  6,  0, 'RU', 'NOVT', 1),
		'Asia/Omsk'				=> array(+1,  6,  0, 'RU', 'OMST', 1),
		'Asia/Oral'				=> array(+1,  4,  0, 'KZ', '',     1),
		'Asia/Phnom_Penh'			=> array(+1,  7,  0, 'KH', '',     0),
		'Asia/Pontianak'			=> array(+1,  7,  0, 'ID', '',     0),
		'Asia/Pyongyang'			=> array(+1,  9,  0, 'KP', '',     0),
		'Asia/Qatar'				=> array(+1,  3,  0, 'QA', '',     0),
		'Asia/Qyzylorda'			=> array(+1,  6,  0, 'KZ', '',     1),
		'Asia/Rangoon'				=> array(+1,  6, 30, 'MM', 'MMT',  0),
		'Asia/Riyadh'				=> array(+1,  3,  0, 'SA', 'AST',  0),
		'Asia/Riyadh87'				=> array(+1,  3,  7, '',   '',     0),
		'Asia/Riyadh88'				=> array(+1,  3,  7, '',   '',     0),
		'Asia/Riyadh89'				=> array(+1,  3,  7, '',   '',     0),
		'Asia/Saigon'				=> array(+1,  7,  0, 'VN', 'ICT',  0),
		'Asia/Sakhalin'				=> array(+1, 10,  0, 'RU', 'SAKT', 1),
		'Asia/Samarkand'			=> array(+1,  5,  0, 'UZ', '',     0),
		'Asia/Seoul'				=> array(+1,  9,  0, 'KR', 'KST',  0),
		'Asia/Shanghai'				=> array(+1,  8,  0, 'CN', 'CST',  0),
		'Asia/Singapore'			=> array(+1,  8,  0, 'SG', '',     0),
		'Asia/Taipei'				=> array(+1,  8,  0, 'TW', 'CST',  0),
		'Asia/Tashkent'				=> array(+1,  5,  0, 'UZ', 'UZT',  0),
		'Asia/Tbilisi'				=> array(+1,  3,  0, 'GE', '',     1),
		'Asia/Tehran'				=> array(+1,  3, 30, 'IR', 'IRT',  1),
		'Asia/Tel_Aviv'				=> array(+1,  2,  0, '',   '',     1),
		'Asia/Thimbu'				=> array(+1,  6,  0, '',   '',     0),
		'Asia/Thimphu'				=> array(+1,  6,  0, 'BT', '',     0),
		'Asia/Tokyo'				=> array(+1,  9,  0, 'JP', 'JST',  0),
		'Asia/Ujung_Pandang'			=> array(+1,  8,  0, '',   '',     0),
		'Asia/Ulaanbaatar'			=> array(+1,  8,  0, 'MN', '',     1),
		'Asia/Ulan_Bator'			=> array(+1,  8,  0,   '', '',     1),
		'Asia/Urumqi'				=> array(+1,  8,  0, 'CN', '',     0),
		'Asia/Vientiane'			=> array(+1,  7,  0, 'LA', '',     0),
		'Asia/Vladivostok'			=> array(+1, 10,  0, 'RU', 'VLAT', 1),
		'Asia/Yakutsk'				=> array(+1,  9,  0, 'RU', 'YAKT', 1),
		'Asia/Yekaterinburg'			=> array(+1,  5,  0, 'RU', 'YEKT', 1),
		'Asia/Yerevan'				=> array(+1,  4,  0, 'AM', '',     1),
		'Atlantic/Azores'			=> array(-1,  1,  0, 'PT', 'AZOT', 1),
		'Atlantic/Bermuda'			=> array(-1,  4,  0, 'BM', '',     1),
		'Atlantic/Canary'			=> array(+1,  0,  0, 'ES', 'WET',  1),
		'Atlantic/Cape_Verde'			=> array(-1,  1,  0, 'CV', 'CVT',  0),
		'Atlantic/Faeroe'			=> array(+1,  0,  0, 'FO', '',     1),
		'Atlantic/Jan_Mayen'			=> array(+1,  1,  0, 'SJ', '',     1),
		'Atlantic/Madeira'			=> array(+1,  0,  0, 'PT', '',     1),
		'Atlantic/Reykjavik'			=> array(+1,  0,  0, 'IS', '',     0),
		'Atlantic/South_Georgia'		=> array(-1,  2,  0, 'GS', 'GST',  0),
		'Atlantic/St_Helena'			=> array(+1,  0,  0, 'SH', '',     0),
		'Atlantic/Stanley'			=> array(-1,  4,  0, 'FK', 'FKST', 1),
		'Australia/ACT'				=> array(+1, 10,  0, '',   '',     1),
		'Australia/Adelaide'			=> array(+1,  9, 30, 'AU', 'CST',  1),
		'Australia/Brisbane'			=> array(+1, 10,  0, 'AU', 'EST',  0),
		'Australia/Broken_Hill'			=> array(+1,  9, 30, 'AU', '',     1),
		'Australia/Canberra'			=> array(+1, 10,  0, '',   '',     1),
		'Australia/Darwin'			=> array(+1,  9, 30, 'AU', 'CST',  0),
		'Australia/Hobart'			=> array(+1, 10,  0, 'AU', 'EST',  1),
		'Australia/LHI'				=> array(+1, 10, 30, '',   '',     1),
		'Australia/Lindeman'			=> array(+1, 10,  0, 'AU', '',     0),
		'Australia/Lord_Howe'			=> array(+1, 10, 30, 'AU', 'LHST', 1),
		'Australia/Melbourne'			=> array(+1, 10,  0, 'AU', '',     1),
		'Australia/NSW'				=> array(+1, 10,  0, '',   '',     1),
		'Australia/North'			=> array(+1,  9, 30, '',   '',     0),
		'Australia/Perth'			=> array(+1,  8,  0, 'AU', 'WST',  0),
		'Australia/Queensland'			=> array(+1, 10,  0, '',   '',     0),
		'Australia/South'			=> array(+1,  9, 30, '',   '',     1),
		'Australia/Sydney'			=> array(+1, 10,  0, 'AU', 'EST',  1),
		'Australia/Tasmania'			=> array(+1, 10,  0, '',   '',     1),
		'Australia/Victoria'			=> array(+1, 10,  0, '',   '',     1),
		'Australia/West'			=> array(+1,  8,  0, '',   '',     0),
		'Australia/Yancowinna'			=> array(+1,  9, 30, '',   '',     1),
		'Brazil/Acre'				=> array(-1,  5,  0, '',   '',     0),
		'Brazil/DeNoronha'			=> array(-1,  2,  0, '',   '',     0),
		'Brazil/East'				=> array(-1,  3,  0, '',   '',     1),
		'Brazil/West'				=> array(-1,  4,  0, '',   '',     0),
		'CET'					=> array(+1,  1,  0, '',   '',     1),
		'CST6CDT'				=> array(-1,  6,  0, '',   '',     1),
		'Canada/Atlantic'			=> array(-1,  4,  0, '',   '',     1),
		'Canada/Central'			=> array(-1,  6,  0, '',   '',     1),
		'Canada/East-Saskatchewan'		=> array(-1,  6,  0, '',   '',     0),
		'Canada/Eastern'			=> array(-1,  5,  0, '',   '',     1),
		'Canada/Mountain'			=> array(-1,  7,  0, '',   '',     1),
		'Canada/Newfoundland'			=> array(-1,  3, 30, '',   '',     1),
		'Canada/Pacific'			=> array(-1,  8,  0, '',   '',     1),
		'Canada/Saskatchewan'			=> array(-1,  6,  0, '',   '',     0),
		'Canada/Yukon'				=> array(-1,  8,  0, '',   '',     1),
		'Chile/Continental'			=> array(-1,  4,  0, '',   '',     1),
		'Chile/EasterIsland'			=> array(-1,  6,  0, '',   '',     1),
		'Cuba'					=> array(-1,  5,  0, '',   '',     1),
		'EET'					=> array(+1,  2,  0, '',   '',     1),
		'EST'					=> array(-1,  5,  0, '',   'EST',  0),
		'EST5EDT'				=> array(-1,  5,  0, '',   '',     1),
		'Egypt'					=> array(+1,  2,  0, '',   '',     1),
		'Eire'					=> array(+1,  0,  0, '',   '',     1),
		'Etc/GMT'				=> array(+1,  0,  0, '',   '',     0),
		'Etc/GMT+0'				=> array(+1,  0,  0, '',   '',     0),
		'Etc/GMT+1'				=> array(-1,  1,  0, '',   '',     0),
		'Etc/GMT+10'				=> array(-1, 10,  0, '',   '',     0),
		'Etc/GMT+11'				=> array(-1, 11,  0, '',   '',     0),
		'Etc/GMT+12'				=> array(-1, 12,  0, '',   '',     0),
		'Etc/GMT+2'				=> array(-1,  2,  0, '',   '',     0),
		'Etc/GMT+3'				=> array(-1,  3,  0, '',   '',     0),
		'Etc/GMT+4'				=> array(-1,  4,  0, '',   '',     0),
		'Etc/GMT+5'				=> array(-1,  5,  0, '',   '',     0),
		'Etc/GMT+6'				=> array(-1,  6,  0, '',   '',     0),
		'Etc/GMT+7'				=> array(-1,  7,  0, '',   '',     0),
		'Etc/GMT+8'				=> array(-1,  8,  0, '',   '',     0),
		'Etc/GMT+9'				=> array(-1,  9,  0, '',   '',     0),
		'Etc/GMT-0'				=> array(+1,  0,  0, '',   '',     0),
		'Etc/GMT-1'				=> array(+1,  1,  0, '',   '',     0),
		'Etc/GMT-10'				=> array(+1, 10,  0, '',   '',     0),
		'Etc/GMT-11'				=> array(+1, 11,  0, '',   '',     0),
		'Etc/GMT-12'				=> array(+1, 12,  0, '',   '',     0),
		'Etc/GMT-13'				=> array(+1, 13,  0, '',   '',     0),
		'Etc/GMT-14'				=> array(+1, 14,  0, '',   '',     0),
		'Etc/GMT-2'				=> array(+1,  2,  0, '',   '',     0),
		'Etc/GMT-3'				=> array(+1,  3,  0, '',   '',     0),
		'Etc/GMT-4'				=> array(+1,  4,  0, '',   '',     0),
		'Etc/GMT-5'				=> array(+1,  5,  0, '',   '',     0),
		'Etc/GMT-6'				=> array(+1,  6,  0, '',   '',     0),
		'Etc/GMT-7'				=> array(+1,  7,  0, '',   '',     0),
		'Etc/GMT-8'				=> array(+1,  8,  0, '',   '',     0),
		'Etc/GMT-9'				=> array(+1,  9,  0, '',   '',     0),
		'Etc/GMT0'				=> array(+1,  0,  0, '',   'GMT',  0),
		'Etc/Greenwich'				=> array(+1,  0,  0, '',   '',     0),
		'Etc/UCT'				=> array(+1,  0,  0, '',   '',     0),
		'Etc/UTC'				=> array(+1,  0,  0, '',   'UTC',  0),
		'Etc/Universal'				=> array(+1,  0,  0, '',   'UTC',  0),
		'Etc/Zulu'				=> array(+1,  0,  0, '',   '',     0),
		'Europe/Amsterdam'			=> array(+1,  1,  0, 'NL', '',     1),
		'Europe/Andorra'			=> array(+1,  1,  0, 'AD', '',     1),
		'Europe/Athens'				=> array(+1,  2,  0, 'GR', '',     1),
		'Europe/Belfast'			=> array(+1,  0,  0, 'GB', '',     1),
		'Europe/Belgrade'			=> array(+1,  1,  0, '',   '',     1),
		'Europe/Berlin'				=> array(+1,  1,  0, 'DE', '',     1),
		'Europe/Bratislava'			=> array(+1,  1,  0, 'SK', '',     1),
		'Europe/Brussels'			=> array(+1,  1,  0, 'BE', '',     1),
		'Europe/Bucharest'			=> array(+1,  2,  0, 'RO', '',     1),
		'Europe/Budapest'			=> array(+1,  1,  0, 'HU', '',     1),
		'Europe/Chisinau'			=> array(+1,  2,  0, 'MD', '',     1),
		'Europe/Copenhagen'			=> array(+1,  1,  0, 'DK', '',     1),
		'Europe/Dublin'				=> array(+1,  0,  0, 'IE', '',     1),
		'Europe/Gibraltar'			=> array(+1,  1,  0, 'GI', '',     1),
		'Europe/Helsinki'			=> array(+1,  2,  0, 'FI', '',     1),
		'Europe/Istanbul'			=> array(+1,  2,  0, 'TR', 'EET',  1),
		'Europe/Kaliningrad'			=> array(+1,  2,  0, 'RU', '',     1),
		'Europe/Kiev'				=> array(+1,  2,  0, 'UA', '',     1),
		'Europe/Lisbon'				=> array(+1,  0,  0, 'PT', '',     1),
		'Europe/Ljubljana'			=> array(+1,  1,  0, 'SI', '',     1),
		'Europe/London'				=> array(+1,  0,  0, 'GB', 'BST',  1),
		'Europe/Luxembourg'			=> array(+1,  1,  0, 'LU', '',     1),
		'Europe/Madrid'				=> array(+1,  1,  0, 'ES', '',     1),
		'Europe/Malta'				=> array(+1,  1,  0, 'MT', '',     1),
		'Europe/Mariehamn'			=> array(+1,  2,  0, '',   '',     1),
		'Europe/Minsk'				=> array(+1,  2,  0, 'BY', 'EET',  1),
		'Europe/Monaco'				=> array(+1,  1,  0, 'MC', '',     1),
		'Europe/Moscow'				=> array(+1,  3,  0, 'RU', 'MSK',  1),
		'Europe/Nicosia'			=> array(+1,  2,  0, '',   '',     1),
		'Europe/Oslo'				=> array(+1,  1,  0, 'NO', '',     1),
		'Europe/Paris'				=> array(+1,  1,  0, 'FR', '',     1),
		'Europe/Prague'				=> array(+1,  1,  0, 'CZ', '',     1),
		'Europe/Riga'				=> array(+1,  2,  0, 'LV', '',     1),
		'Europe/Rome'				=> array(+1,  1,  0, 'IT', 'CET',  1),
		'Europe/Samara'				=> array(+1,  4,  0, 'RU', 'SAMT', 1),
		'Europe/San_Marino'			=> array(+1,  1,  0, 'SM', '',     1),
		'Europe/Sarajevo'			=> array(+1,  1,  0, 'BA', '',     1),
		'Europe/Simferopol'			=> array(+1,  2,  0, 'UA', '',     1),
		'Europe/Skopje'				=> array(+1,  1,  0, 'MK', '',     1),
		'Europe/Sofia'				=> array(+1,  2,  0, 'BG', '',     1),
		'Europe/Stockholm'			=> array(+1,  1,  0, 'SE', '',     1),
		'Europe/Tallinn'			=> array(+1,  2,  0, 'EE', '',     1),
		'Europe/Tirane'				=> array(+1,  1,  0, 'AL', '',     1),
		'Europe/Tiraspol'			=> array(+1,  2,  0, '',   '',     1),
		'Europe/Uzhgorod'			=> array(+1,  2,  0, 'UA', '',     1),
		'Europe/Vaduz'				=> array(+1,  1,  0, 'LI', '',     1),
		'Europe/Vatican'			=> array(+1,  1,  0, 'VA', '',     1),
		'Europe/Vienna'				=> array(+1,  1,  0, 'AT', '',     1),
		'Europe/Vilnius'			=> array(+1,  2,  0, 'LT', 'EET',  1),
		'Europe/Warsaw'				=> array(+1,  1,  0, 'PL', '',     1),
		'Europe/Zagreb'				=> array(+1,  1,  0, 'HR', '',     1),
		'Europe/Zaporozhye'			=> array(+1,  2,  0, 'UA', '',     1),
		'Europe/Zurich'				=> array(+1,  1,  0, 'CH', '',     1),
		'Factory'				=> array(+1,  0,  0, '',   '',     0),
		'GB'					=> array(+1,  0,  0, '',   '',     1),
		'GB-Eire'				=> array(+1,  0,  0, '',   '',     1),
		'GMT'					=> array(+1,  0,  0, '',   'GMT',  0),
		'GMT+0'					=> array(+1,  0,  0, '',   'GMT',  0),
		'GMT-0'					=> array(+1,  0,  0, '',   'GMT',  0),
		'GMT0'					=> array(+1,  0,  0, '',   'GMT',  0),
		'Greenwich'				=> array(+1,  0,  0, '',   'GMT',  0),
		'HST'					=> array(-1, 10,  0, '',   '',     0),
		'Hongkong'				=> array(+1,  8,  0, '',   '',     0),
		'Iceland'				=> array(+1,  0,  0, '',   '',     0),
		'Indian/Antananarivo'			=> array(+1,  3,  0, 'MG', '',     0),
		'Indian/Chagos'				=> array(+1,  6,  0, 'IO', '',     0),
		'Indian/Christmas'			=> array(+1,  7,  0, 'CX', '',     0),
		'Indian/Cocos'				=> array(+1,  6, 30, 'CC', '',     0),
		'Indian/Comoro'				=> array(+1,  3,  0, 'KM', '',     0),
		'Indian/Kerguelen'			=> array(+1,  5,  0, 'TF', '',     0),
		'Indian/Mahe'				=> array(+1,  4,  0, 'SC', '',     0),
		'Indian/Maldives'			=> array(+1,  5,  0, 'MV', '',     0),
		'Indian/Mauritius'			=> array(+1,  4,  0, 'MU', '',     0),
		'Indian/Mayotte'			=> array(+1,  3,  0, 'YT', '',     0),
		'Indian/Reunion'			=> array(+1,  4,  0, 'RE', '',     0),
		'Iran'					=> array(+1,  3, 30, 'IR', '',     1),
		'Israel'				=> array(+1,  2,  0, 'IL', '',     1),
		'Jamaica'				=> array(-1,  5,  0, 'JM', '',     0),
		'Japan'					=> array(+1,  9,  0, 'JP', 'JST',  0),
		'Kwajalein'				=> array(+1, 12,  0, '',   '',     0),
		'Libya'					=> array(+1,  2,  0, 'LY', '',     0),
		'MET'					=> array(+1,  1,  0, '',   '',     1),
		'MST'					=> array(-1,  7,  0, '',   'MST',  0),
		'MST7MDT'				=> array(-1,  7,  0, '',   '',     1),
		'Mexico/BajaNorte'			=> array(-1,  8,  0, '',   '',     1),
		'Mexico/BajaSur'			=> array(-1,  7,  0, '',   '',     1),
		'Mexico/General'			=> array(-1,  6,  0, '',   '',     1),
		'Mideast/Riyadh87'			=> array(+1,  3,  7, '',   '',     0),
		'Mideast/Riyadh88'			=> array(+1,  3,  7, '',   '',     0),
		'Mideast/Riyadh89'			=> array(+1,  3,  7, '',   '',     0),
		'NZ'					=> array(+1, 12,  0, '',   '',     1),
		'NZ-CHAT'				=> array(+1, 12, 45, '',   '',     1),
		'Navajo'				=> array(-1,  7,  0, '',   '',     1),
		'PRC'					=> array(+1,  8,  0, '',   '',     0),
		'PST8PDT'				=> array(-1,  8,  0, '',   '',     1),
		'Pacific/Apia'				=> array(-1, 11,  0, 'WS', 'WST',  0),
		'Pacific/Auckland'			=> array(+1, 12,  0, 'NZ', 'NZDT', 1),
		'Pacific/Chatham'			=> array(+1, 12, 45, 'NZ', 'CHADT',1),
		'Pacific/Easter'			=> array(-1,  6,  0, 'CL', 'EASST',1),
		'Pacific/Efate'				=> array(+1, 11,  0, 'VU', '',     0),
		'Pacific/Enderbury'			=> array(+1, 13,  0, 'KI', 'PHOT', 0),
		'Pacific/Fakaofo'			=> array(-1, 10,  0, 'TK', '',     0),
		'Pacific/Fiji'				=> array(+1, 12,  0, 'FJ', 'FJT',  0),
		'Pacific/Funafuti'			=> array(+1, 12,  0, 'TV', '',     0),
		'Pacific/Galapagos'			=> array(-1,  6,  0, 'EC', 'GALT', 0),
		'Pacific/Gambier'			=> array(-1,  9,  0, 'PF', 'GAMT', 0),
		'Pacific/Guadalcanal'			=> array(+1, 11,  0, 'SB', 'SBT',  0),
		'Pacific/Guam'				=> array(+1, 10,  0, 'GU', 'ChST', 0),
		'Pacific/Honolulu'			=> array(-1, 10,  0, 'US', 'HST',  0),
		'Pacific/Johnston'			=> array(-1, 10,  0, 'UM', '',     0),
		'Pacific/Kiritimati'			=> array(+1, 14,  0, 'KI', 'LINT', 0),
		'Pacific/Kosrae'			=> array(+1, 11,  0, 'FM', '',     0),
		'Pacific/Kwajalein'			=> array(+1, 12,  0, 'MH', '',     0),
		'Pacific/Majuro'			=> array(+1, 12,  0, 'MH', '',     0),
		'Pacific/Marquesas'			=> array(-1,  9, 30, 'PF', 'MART', 0),
		'Pacific/Midway'			=> array(-1, 11,  0, 'UM', '',     0),
		'Pacific/Nauru'				=> array(+1, 12,  0, 'NR', '',     0),
		'Pacific/Niue'				=> array(-1, 11,  0, 'NU', '',     0),
		'Pacific/Norfolk'			=> array(+1, 11, 30, 'NF', 'NFT',  0),
		'Pacific/Noumea'			=> array(+1, 11,  0, 'NC', '',     0),
		'Pacific/Pago_Pago'			=> array(-1, 11,  0, 'AS', '',     0),
		'Pacific/Palau'				=> array(+1,  9,  0, 'PW', '',     0),
		'Pacific/Pitcairn'			=> array(-1,  8,  0, 'PN', 'PST',  0),
		'Pacific/Ponape'			=> array(+1, 11,  0, 'FM', '',     0),
		'Pacific/Port_Moresby'			=> array(+1, 10,  0, 'PG', '',     0),
		'Pacific/Rarotonga'			=> array(-1, 10,  0, 'CK', 'CKT',  0),
		'Pacific/Saipan'			=> array(+1, 10,  0, 'MP', '',     0),
		'Pacific/Samoa'				=> array(-1, 11,  0, '',   '',     0),
		'Pacific/Tahiti'			=> array(-1, 10,  0, 'PF', 'TAHT', 0),
		'Pacific/Tarawa'			=> array(+1, 12,  0, 'KI', 'GILT', 0),
		'Pacific/Tongatapu'			=> array(+1, 13,  0, 'TO', '',     0),
		'Pacific/Truk'				=> array(+1, 10,  0, 'FM', '',     0),
		'Pacific/Wake'				=> array(+1, 12,  0, 'UM', '',     0),
		'Pacific/Wallis'			=> array(+1, 12,  0, 'WF', '',     0),
		'Pacific/Yap'				=> array(+1, 10,  0, 'FM', '',     0),
		'Poland'				=> array(+1,  1,  0, 'PL', '',     1),
		'Portugal'				=> array(+1,  0,  0, 'PT', '',     1),
		'ROC'					=> array(+1,  8,  0, '',   '',     0),
		'ROK'					=> array(+1,  9,  0, 'KR', 'KST',  0), // Republic of Korea
		'Singapore'				=> array(+1,  8,  0, 'SG', '',     0),
		'SystemV/AST4'				=> array(-1,  4,  0, '',   'AST',  0),
		'SystemV/AST4ADT'			=> array(-1,  4,  0, '',   '',     1),
		'SystemV/CST6'				=> array(-1,  6,  0, '',   'CST',  0),
		'SystemV/CST6CDT'			=> array(-1,  6,  0, '',   '',     1),
		'SystemV/EST5'				=> array(-1,  5,  0, '',   '',     0),
		'SystemV/EST5EDT'			=> array(-1,  5,  0, '',   '',     1),
		'SystemV/HST10'				=> array(-1, 10,  0, '',   '',     0),
		'SystemV/MST7'				=> array(-1,  7,  0, '',   '',     0),
		'SystemV/MST7MDT'			=> array(-1,  7,  0, '',   '',     1),
		'SystemV/PST8'				=> array(-1,  8,  0, '',   '',     0),
		'SystemV/PST8PDT'			=> array(-1,  8,  0, '',   '',     1),
		'SystemV/YST9'				=> array(-1,  9,  0, '',   '',     0),
		'SystemV/YST9YDT'			=> array(-1,  9,  0, '',   '',     1),
		'Turkey'				=> array(+1,  2,  0, 'TR', '',     1),
		'UCT'					=> array(+1,  0,  0, '',   '',     0),
		'US/Alaska'				=> array(-1,  9,  0, '',   '',     1),
		'US/Aleutian'				=> array(-1, 10,  0, '',   '',     1),
		'US/Arizona'				=> array(-1,  7,  0, '',   '',     0),
		'US/Central'				=> array(-1,  6,  0, '',   '',     1),
		'US/East-Indiana'			=> array(-1,  5,  0, '',   '',     0),
		'US/Eastern'				=> array(-1,  5,  0, '',   '',     1),
		'US/Hawaii'				=> array(-1, 10,  0, 'US', '',     0),
		'US/Indiana-Starke'			=> array(-1,  5,  0, '',   '',     0),
		'US/Michigan'				=> array(-1,  5,  0, '',   '',     1),
		'US/Mountain'				=> array(-1,  7,  0, '',   '',     1),
		'US/Pacific'				=> array(-1,  8,  0, '',   '',     1),
		'US/Pacific-New'			=> array(-1,  8,  0, '',   '',     1),
		'US/Samoa'				=> array(-1, 11,  0, '',   '',     0),
		'UTC'					=> array(+1,  0,  0, '',   'UTC',  0),
		'Universal'				=> array(+1,  0,  0, '',   'UTC',  0),
		'W-SU'					=> array(+1,  3,  0, '',   '',     1),
		'WET'					=> array(+1,  0,  0, '',   '',     1),
		'Zulu'					=> array(+1,  0,  0, '',   '',     0),
	);

	function timezone($x='')
	{
		$this->country = strtoupper( $x );
	}

	function get_zone()
	{
		foreach($this->tz as $_key => $_tz) {
			if ($_tz[3] == $this->country) {
				if (! empty($_tz[4])) return $_tz[4];
			}
		}
		return "";
	}

	function get_zonetime($dst=0)
	{
		foreach($this->tz as $_key => $_tz) {
			if ($_tz[3] == $this->country) {
				$_dst = ($dst && $_tz[5]) ? (3600 * $_tz[0]) : 0;
				$h = $_tz[1] * 3600;
				$i = $_tz[2] * 60;
				return ($h + $i + $_dst) * $_tz[0];
			}
		}
		return 0;
	}

	function get_zoneinfo($name)
	{
		if (empty($this->tz[$name])) return array();
		return $this->tz[$name];
	}


}

/*
$obj = new timezone('TW');
// $obj = new timezone('LT');
// $obj = new timezone('TC');

print "ZONE=" . $obj->get_zone() ."\n";
print "ZONETIME=" . $obj->get_zonetime(1) . "\n";
*/

?>
