#!/bin/sh
msgfmt -o ../locale/ja/LC_MESSAGES/pukiwiki.mo pukiwiki.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/add.mo add.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/addline.mo addline.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/article.mo article.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/back.mo back.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/calendar2.mo calendar2.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/calendar_viewer.mo calendar_viewer.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/comment.mo comment.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/deleted.mo deleted.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/diff.mo diff.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/freeze.mo freeze.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/interwiki.mo interwiki.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/include.mo include.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/insert.mo insert.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/list.mo list.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/ls2.mo ls2.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/navi.mo navi.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/newpage.mo newpage.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/memo.mo memo.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/minicalendar.mo minicalendar.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/minicalendar_viewer.mo minicalendar_viewer.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/pcomment.mo pcomment.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/search.mo search.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/source.mo source.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/template.mo template.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/tracker.mo tracker.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/unfreeze.mo unfreeze.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/vote.mo vote.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/versionlist.mo versionlist.ja.po
msgfmt -o ../locale/ja/LC_MESSAGES/yetlist.mo yetlist.ja.po
