<?php
/**
 * AviSynth キーワード定義ファイル
 */

$switchHash['"'] = PLUGIN_CODE_NONESCAPE_LITERAL;  // " はエスケープ文字ではない
$mkoutline = $option['outline'] = false; // アウトラインモード不可
$capital = true;                    // 予約語の大文字小文字を区別しない

// コメント定義
$switchHash['#'] = PLUGIN_CODE_COMMENT;    // コメントは # から改行まで
$code_comment = Array(
	'#' => Array(
				 Array('/^#/', "\n", 1),
	)
);

$code_css = Array(
  'operator',		// オペレータ関数
  'identifier',	// その他の識別子
  'function',		// 標準関数
  'system',		// 処理系組み込みの奴 __stdcall とか
  );

$code_keyword = Array(
		//ScriptVariables
		'global' => 2,
		'bool' => 2,
		'int' => 2,
		'float' => 2,
		'string' => 2,
		'val' => 2,
		'clip' => 2,
		
		//ScriptFunctions
		'catch' => 2,
		'default' => 2,
		'nop' => 2,
		'try' => 2,

		'abs' => 3,
		'apply' => 3,
		'asserteval' => 3,
		'assert' => 3,
		'ceil' => 3,
		'cos' => 3,
		'defined' => 3,
		'eval' => 3,
		'exp' => 3,
		'exist' => 3,
		'floor' => 3,
		'frac' => 3,
		'findstr' => 3,
		'hexvalue' => 3,
		'isbool' => 3,
		'isint' => 3,
		'isfloat' => 3,
		'isstring' => 3,
		'isclip' => 3,
		'log' => 3,
		'lcase' => 3,
		'leftstr' => 3,
		'midstr' => 3,
		'round' => 3,
		'rand' => 3,
		'revstr' => 3,
		'rightstr' => 3,
		'sin' => 3,
		'sqrt' => 3,
		'sign' => 3,
		'strlen' => 3,
		'setmemorymax' => 3,
		'setworkingdir' => 3,
		'select' => 3,
		'pi' => 3,
		'pow' => 3,
		'ucase' => 3,
		'value' => 3,
		'versionnumber' => 3,
		'versionstring' => 3,
		
		//Builtin filters
		'addborders' => 3,
		'alignedsplice' => 3,
		'amplifydb' => 3,
		'amplify' => 3,
		'animate' => 3,
		'applyrange' => 3,
		'assumebff' => 3,
		'assumefieldbased' => 3,
		'assumefps' => 3,
		'assumeframebased' => 3,
		'assumesamplerate' => 3,
		'assumetff' => 3,
		'audiodub' => 3,
		'avifilesource' => 3,
		'avisource' => 3,
		'bicubicresize' => 3,
		'bilinearresize' => 3,
		'blackness' => 3,
		'blankclip' => 3,
		'blur' => 3,
		'bob' => 3,
		'changefps' => 3,
		'colorbars' => 3,
		'colorkeymask' => 3,
		'coloryuv' => 3,
		'compare' => 3,
		'complementparity' => 3,
		'conditionalfilter' => 3,
		'convertaudioto8bit' => 3,
		'convertaudioto16bit' => 3,
		'convertaudioto24bit' => 3,
		'convertaudioto32bit' => 3,
		'convertaudiotofloat' => 3,
		'converttomono' => 3,
		'convertbacktoyuy2' => 3,
		'convertfps' => 3,
		'converttorgb' => 3,
		'converttorgb24' => 3,
		'converttorgb32' => 3,
		'converttoyuy2' => 3,
		'converttoyv12' => 3,
		'cropbottom' => 3,
		'crop' => 3,
		'delayaudio' => 3,
		'deleteframe' => 3,
		'directshowsource' => 3,
		'dissolve' => 3,
		'doubleweave' => 3,
		'duplicateframe' => 3,
		'ensurevbrmp3sync' => 3,
		'fadein2' => 3,
		'fadein' => 3,
		'fadeio2' => 3,
		'fadeio' => 3,
		'fadeout2' => 3,
		'fadeout' => 3,
		'fixbrokenchromaupsampling' => 3,
		'fixluminance' => 3,
		'fliphorizontal' => 3,
		'flipvertical' => 3,
		'frameevaluate' => 3,
		'freezeframe' => 3,
		'generalconvolution' => 3,
		'getchannel' => 3,
		'getleftchannel' => 3,
		'getrightchannel' => 3,
		'greyscale' => 3,
		'highpassaudio' => 3,
		'histogram' => 3,
		'horizontalreduceby2' => 3,
		'hsiadjust' => 3,
		'imagereader' => 3,
		'imagesource' => 3,
		'imagewriter' => 3,
		'import' => 3,
		'info' => 3,
		'interleave' => 3,
		'invert' => 3,
		'ipcsource' => 3,
		'killaudio' => 3,
		'lanczosresize' => 3,
		'lanczos4resize' => 3,
		'layer' => 3,
		'letterbox' => 3,
		'levels' => 3,
		'limiter' => 3,
		'loop' => 3,
		'lowpassaudio' => 3,
		'mask' => 3,
		'mergechannels' => 3,
		'mergechroma' => 3,
		'mergeluma' => 3,
		'messageclip' => 3,
		'mixaudio' => 3,
		'monotostereo' => 3,
		'normalize' => 3,
		'opendmlsource' => 3,
		'overlay' => 3,
		'peculiarblend' => 3,
		'pointresize' => 3,
		'pulldown' => 3,
		'reduceby2' => 3,
		'resetmask' => 3,
		'reverse' => 3,
		'resampleaudio' => 3,
		'rgbadjust' => 3,
		'scriptclip' => 3,
		'segmentedavisource' => 3,
		'segmenteddirectshowsource' => 3,
		'selecteven' => 3,
		'selectevery' => 3,
		'selectodd' => 3,
		'selectrangeevery' => 3,
		'separatefields' => 3,
		'sharpen' => 3,
		'showalpha' => 3,
		'showfiveversions' => 3,
		'showframenumber' => 3,
		'showsmpte' => 3,
		'spatialsoften' => 3,
		'ssrc' => 3,
		'stackhorizontal' => 3,
		'stackvertical' => 3,
		'subtitle' => 3,
		'subtract' => 3,
		'supereq' => 3,
		'swapuv' => 3,
		'swapfields' => 3,
		'tcpserver' => 3,
		'tcpsource' => 3,
		'temporalsoften' => 3,
		'timestretch' => 3,
		'tone' => 3,
		'trim' => 3,
		'turn180' => 3,
		'turnleft' => 3,
		'turnright' => 3,
		'tweak' => 3,
		'unalignedsplice' => 3,
		'utoy' => 3,
		'vtoy' => 3,
		'ytouv' => 3,
		'version' => 3,
		'verticalreduceby2' => 3,
		'wavsource' => 3,
		'weave' => 3,
		'writefileif' => 3,
		'writefilestart' => 3,
		'writefileend' => 3,
		'writefile' => 3,

		'loadplugin' => 3,
		'loadvirtualdubplugin' => 3,
		'loadvfapiplugin' => 3,
		
		//ClipProperties
		'width' => 3,
		'height' => 3,
		'framecount' => 3,
		'frameratenumerator' => 3,
		'frameratedenominator' => 3,
		'framerate' => 3,
		'audiorate' => 3,
		'audiolengthf' => 3,
		'audiolength' => 3,
		'audiochannels' => 3,
		'audiobits' => 3,
		'isaudiofloat' => 3,
		'isaudioint' => 3,
		'isplanar' => 3,
		'isrgb24' => 3,
		'isrgb32' => 3,
		'isrgb' => 3,
		'isyuv' => 3,
		'isyuy2' => 3,
		'isyv12' => 3,
		'isfieldbased' => 3,
		'isframebased' => 3,
		'isinterleaved' => 3,
		'getparity' => 3,
		
		//Others
		'last' => 2,
		'function' => 2,
		'return' => 2,
		'false' => 2,
		'true' => 2,
  );
?>
